# safe: true # need to disable this to add tailwind, see with someone why
markdown: kramdown
exclude: [node_modules, bower_components, vendor]
url: https://www.jhipster.tech
github_repository_url: https://github.com/jhipster/jhipster.github.io
kramdown:
  input: GFM
plugins_dir:
  - jekyll-redirect-from
  - jemoji
plugins:
  - jekyll-postcss
postcss:
  cache: false
whitelist:
  - jekyll-redirect-from
  - jemoji
  # defaults: # see first comment
  # -
  #   scope:
  #     path: "" # an empty string here means all files in the project
  #   values:
  #     layout: "default"
